baseURL = "https://sikhanh2003.github.io/FCAJ-Workshop/"
relativeURLs = false
canonifyURLs = true
defaultContentLanguage = "en"
theme = "hugo-theme-learn"

# Cấu hình Output cho tính năng tìm kiếm
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  # Theme variant: "workshop" là bản chuẩn cho AWS
  themeVariant = "workshop"
  author = "dinhviethieu2910@gmail.com"
  description = "Worklog Internship Report"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  # Quan trọng: giúp load CSS mượt hơn trên GitHub Pages
  disableAssetsBusting = true

[languages]
  [languages.en]
    title = "Worklog :: Internship Report"
    weight = 1
    languageName = "English"
    [[languages.en.menu.shortcuts]]
      name = "<i class='fab fa-facebook'></i> AWS Study Group"
      url = "https://www.facebook.com/groups/awsstudygroupfcj/"
      weight = 20

  [languages.vi]
    title = "Worklog :: Báo cáo thực tập"
    weight = 2
    languageName = "Tiếng Việt"
    [[languages.vi.menu.shortcuts]]
      name = "<i class='fab fa-facebook'></i> AWS Study Group"
      url = "https://www.facebook.com/groups/awsstudygroupfcj/"
      weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true